### ISSUE TITLE
Does it work for python-telegram-bot v20.xx?

### ISSUE THREAD

**Issue by tech-fever** [GamePad64/python-telegram-bot-django-persistence#41]
Does it work for [python-telegram-bot v20.xx](https://github.com/python-telegram-bot/python-telegram-bot)?

**Comment by DzIGIBAUER** [comment]
I just downloaded this and latest version of python-telegram-bot 20.3 and I had to re implement the `persistence.py` since
```py
from telegram.ext.utils.types import BD, CD, UD, CDCData, ConversationDict
```
should now be
```py
from telegram.ext._utils.types import BD, CD, UD, CDCData, ConversationDict #the underscore
```

**Comment by GamePad64** [comment]
Support for 20.x is added in 0.2.x
